"""
Tests for markdown_lite — the constructs both site converters were missing.

Reports and docs rendered bullet lists, italics and horizontal rules as literal
text. Adding italics is the risky part: model names in this project are full of
underscores (`ha_live_actual`, `pressure_long_window`), and a naive `_(.+?)_`
turns them into `ha<em>live</em>actual` across every page.
"""

import pytest

from markdown_lite import apply_inline, convert_horizontal_rules, convert_lists
from md_to_html import markdown_to_html


# ---------------------------------------------------------------------------
# Emphasis must not touch identifiers
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("text", [
    "ha_live_actual",
    "pressure_long_window and pressure_combined",
    "model_ha_live vs model_tuned",
    "a_b_c",
    "sensor.outside_dew_point_spread_trend",
    "snake_case_everywhere in one_line of prose",
])
def test_underscored_identifiers_are_left_alone(text):
    assert apply_inline(text) == text


@pytest.mark.parametrize("text,expected", [
    ("_emphasis_", "<em>emphasis</em>"),
    ("*emphasis*", "<em>emphasis</em>"),
    ("a _phrase here_ mid-sentence", "a <em>phrase here</em> mid-sentence"),
])
def test_real_emphasis_is_converted(text, expected):
    assert apply_inline(text) == expected


def test_emphasis_spanning_an_identifier():
    """The real report footer: markers at the edges, underscores inside."""
    text = "_Report generated by daily_analysis.py at 2026-08-13T20:05:43Z_"
    assert apply_inline(text) == \
        "<em>Report generated by daily_analysis.py at 2026-08-13T20:05:43Z</em>"


def test_bold_markers_are_not_mistaken_for_emphasis():
    """apply_inline runs after bold; any leftover ** must survive intact."""
    assert apply_inline("**already bold**") == "**already bold**"


def test_emphasis_needs_content():
    assert apply_inline("a _ b _ c") == "a _ b _ c"


# ---------------------------------------------------------------------------
# Lists
# ---------------------------------------------------------------------------

def test_bullets_become_a_list():
    out = convert_lists("- Rain hours: 14\n- Dry hours: 155\n")
    assert out.count("<li>") == 2
    assert out.strip().startswith("<ul>")
    assert out.strip().endswith("</ul>")


def test_separate_blocks_become_separate_lists():
    out = convert_lists("- a\n- b\n\ntext\n\n- c\n")
    assert out.count("<ul>") == 2


def test_prose_containing_a_dash_is_not_a_list():
    assert "<li>" not in convert_lists("temperature - dew point = spread")


def test_asterisk_bullets_also_work():
    assert convert_lists("* one\n").count("<li>") == 1


# ---------------------------------------------------------------------------
# Horizontal rules
# ---------------------------------------------------------------------------

def test_rule_is_converted():
    assert convert_horizontal_rules("a\n---\nb") == "a\n<hr>\nb"


def test_table_separator_is_not_a_rule():
    """`|---|---|` belongs to the table pass and must reach it intact."""
    text = "| Model | F1 |\n|-------|:---:|\n| tuned | 0.273 |"
    assert convert_horizontal_rules(text) == text


# ---------------------------------------------------------------------------
# End to end through the report converter
# ---------------------------------------------------------------------------

def test_report_renders_lists_italics_and_rules():
    md = """# Daily Model Analysis — 2026-08-13

**Source data ranges:**

- Home Assistant: 1033 rows
- Open Meteo: 1056 rows

---

_N/A means no threshold reached the precision floor._
"""
    html = markdown_to_html(md, "2026-08-13")

    assert "<ul>" in html and html.count("<li>") == 2
    assert "<hr>" in html
    assert "<em>N/A means no threshold reached the precision floor.</em>" in html
    assert "- Home Assistant" not in html


def test_report_table_still_works_and_is_wrapped():
    md = """## Model Performance (7-day window)

| Model | F1 | Precision | Recall |
|-------|:---:|:---------:|:------:|
| ha_live_actual | N/A | N/A | N/A |
| combined | 0.273 | 0.375 | 0.214 |
"""
    html = markdown_to_html(md, "r")

    assert '<div class="table-wrap">' in html
    assert html.count("</tbody></table></div>") == 1
    # The identifier must survive the italics pass and stay one table cell.
    assert "<td>ha_live_actual</td>" in html
