#!/usr/bin/env bash
# One-shot privileged bootstrap of the backend on a server. Idempotent:
# safe to re-run after config or code changes.
#
#   sudo bash deploy/bootstrap.sh \
#       --server-name www.example.com \
#       --nginx-site /etc/nginx/sites-enabled/mysite \
#       [--docker-user someuser] [--skip-nginx] [--public-url URL]
#
# What it does:
#   1. git pull (as the repo owner, not root)
#   2. optionally adds --docker-user to the docker group
#   3. frees the backend port and starts the compose stack (build on the
#      server, per #234), runs alembic migrations
#   4. generates an nginx location snippet from deploy/.env values and
#      includes it into the HTTPS server block of --nginx-site
#      (config backed up; nginx -t gates the reload)
#   5. smoke-tests the local port and, if given, the public URL
#
# Server-specific values (port, path prefix) come from deploy/.env next
# to this script:  BACKEND_PORT (7010), ROOT_PATH (e.g. /rain-api).
# Nothing host-specific lives in the repository.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

SERVER_NAME=""
NGINX_SITE=""
DOCKER_USER=""
PUBLIC_URL=""
SKIP_NGINX=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --server-name) SERVER_NAME="$2"; shift 2 ;;
        --nginx-site)  NGINX_SITE="$2";  shift 2 ;;
        --docker-user) DOCKER_USER="$2"; shift 2 ;;
        --public-url)  PUBLIC_URL="$2";  shift 2 ;;
        --skip-nginx)  SKIP_NGINX=1;     shift ;;
        *) echo "Unknown argument: $1" >&2; exit 2 ;;
    esac
done

if [[ $EUID -ne 0 ]]; then
    echo "Run with sudo: this script manages docker and nginx" >&2
    exit 2
fi
if [[ $SKIP_NGINX -eq 0 && ( -z $SERVER_NAME || -z $NGINX_SITE ) ]]; then
    echo "--server-name and --nginx-site are required (or pass --skip-nginx)" >&2
    exit 2
fi

# Per-server settings
BACKEND_PORT=7010
ROOT_PATH=""
if [[ -f "$SCRIPT_DIR/.env" ]]; then
    # shellcheck disable=SC1091
    source "$SCRIPT_DIR/.env"
fi

REPO_OWNER="$(stat -c %U "$REPO_DIR")"
OWNER_UID="$(id -u "$REPO_OWNER")"
OWNER_GID="$(id -g "$REPO_OWNER")"
COMPOSE=(docker compose -f "$SCRIPT_DIR/docker-compose.yml")
export BACKEND_PORT ROOT_PATH
export BACKEND_UID="$OWNER_UID" BACKEND_GID="$OWNER_GID"

echo "== repo: pull latest (as $REPO_OWNER)"
sudo -u "$REPO_OWNER" git -C "$REPO_DIR" pull --ff-only || \
    echo "   (pull failed or offline — deploying the checked-out revision)"

if [[ -n $DOCKER_USER ]]; then
    echo "== docker group: adding $DOCKER_USER (takes effect on next login)"
    usermod -aG docker "$DOCKER_USER"
fi

if [[ ! -f "$REPO_DIR/backend/.env" ]]; then
    echo "backend/.env is missing — create it first (see deploy/README.md)" >&2
    exit 1
fi

echo "== backend: build image"
"${COMPOSE[@]}" build

echo "== backend: stop whatever holds port $BACKEND_PORT"
"${COMPOSE[@]}" down --remove-orphans 2>/dev/null || true
# A hand-started uvicorn (pre-compose deployments) may still hold the port
fuser -k "${BACKEND_PORT}/tcp" 2>/dev/null || pkill -f "uvicorn app.main" || true
sleep 1

echo "== backend: migrate and start"
"${COMPOSE[@]}" run --rm backend python -m alembic upgrade head
"${COMPOSE[@]}" up -d

if [[ $SKIP_NGINX -eq 0 ]]; then
    echo "== nginx: install snippet"
    if [[ -z $ROOT_PATH ]]; then
        echo "ROOT_PATH is empty in deploy/.env — path-prefix proxying needs one (e.g. /rain-api)" >&2
        exit 1
    fi
    SNIPPET=/etc/nginx/snippets/rain-api.conf
    mkdir -p /etc/nginx/snippets
    cat > "$SNIPPET" << EOF
# Generated by deploy/bootstrap.sh — regenerate by re-running it.
location = $ROOT_PATH {
    return 301 $ROOT_PATH/;
}

location $ROOT_PATH/ {
    proxy_pass         http://127.0.0.1:$BACKEND_PORT/;
    proxy_redirect     off;
    proxy_http_version 1.1;
    proxy_set_header   Host \$host;
    proxy_set_header   X-Real-IP \$remote_addr;
    proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto \$scheme;
}
EOF

    INCLUDE_LINE="    include $SNIPPET; # rain-analysis backend"
    if grep -qF "$SNIPPET" "$NGINX_SITE"; then
        echo "   include already present in $NGINX_SITE"
    else
        cp "$NGINX_SITE" "$NGINX_SITE.bak.$(date +%s)"
        awk -v inc="$INCLUDE_LINE" -v name="$SERVER_NAME" '
            { print }
            !done && $0 ~ ("server_name[ \t]+" name ";") { print inc; done=1 }
        ' "$NGINX_SITE" > "$NGINX_SITE.tmp"
        if ! grep -qF "$SNIPPET" "$NGINX_SITE.tmp"; then
            rm -f "$NGINX_SITE.tmp"
            echo "   could not find 'server_name $SERVER_NAME;' in $NGINX_SITE" >&2
            exit 1
        fi
        mv "$NGINX_SITE.tmp" "$NGINX_SITE"
        echo "   include inserted (backup kept next to the config)"
    fi

    nginx -t
    systemctl reload nginx
fi

echo "== smoke test"
sleep 3
curl -sf "http://127.0.0.1:${BACKEND_PORT}/health" && echo && echo "   local port: OK"
if [[ -n $PUBLIC_URL ]]; then
    curl -sf "${PUBLIC_URL%/}/health" && echo && echo "   public URL: OK"
fi

echo "== done"
