"""
markdown_lite.py — the markdown constructs both site converters need.
=====================================================================

`md_to_html.py` (daily reports) and `convert_docs_to_html.py` (documentation)
each grew their own partial markdown converter, and between them they handled
different subsets: reports lost bullet lists, italics and horizontal rules to
literal text, documentation lost lists and italics. Those live here once.

Italic handling is the fiddly part. Model names in this project are full of
underscores — `ha_live_actual`, `pressure_long_window` — so the obvious
``_(.+?)_`` turns them into ``ha<em>live</em>actual``. The patterns below only
treat a marker as emphasis when it sits on a word boundary, which leaves
identifiers alone while still catching ``_Report generated by daily_analysis.py_``
where the closing marker follows a non-space and ends the run.
"""

from __future__ import annotations

import re

__all__ = ["apply_inline", "convert_horizontal_rules", "convert_lists"]


# Opening marker: not preceded by a word character, followed by non-space.
# Closing marker: preceded by non-space, not followed by a word character.
_EM_UNDERSCORE = re.compile(r"(?<![\w\\])_(?=\S)(.+?)(?<=\S)_(?![\w])")
_EM_STAR = re.compile(r"(?<![\w*\\])\*(?=\S)([^*\n]+?)(?<=\S)\*(?![\w*])")

_HR = re.compile(r"^\s*---+\s*$", re.MULTILINE)

_LIST_ITEM = re.compile(r"^[-*] +(.+)$", re.MULTILINE)
_LIST_BLOCK = re.compile(r"(?:^<li>.*</li>\n?)+", re.MULTILINE)


def apply_inline(text: str) -> str:
    """Emphasis markers that survive underscore-heavy identifiers.

    Run this *after* bold (``**``), so the double markers are already gone.
    """
    text = _EM_UNDERSCORE.sub(r"<em>\1</em>", text)
    return _EM_STAR.sub(r"<em>\1</em>", text)


def convert_horizontal_rules(text: str) -> str:
    """``---`` on its own line becomes a rule.

    Table separators (``|---|---|``) start with a pipe and are untouched, so
    this must still run before the table pass consumes those lines.
    """
    return _HR.sub("<hr>", text)


def convert_lists(text: str) -> str:
    """Bullet lists to ``<ul>``. Nesting is not supported and not used."""
    text = _LIST_ITEM.sub(r"<li>\1</li>", text)
    return _LIST_BLOCK.sub(lambda m: f"<ul>\n{m.group(0).rstrip()}\n</ul>\n", text)
